spring:
  data:
    r2dbc:
      repositories:
        enabled: true
  r2dbc:
    password: P4$$W0RddD
    pool:
      enabled: true
      initial-size: 10
      max-idle-time: 1m
      max-size: 30
    url: r2dbc:postgresql://localhost:5432/r2dbc
    username: postgres
