jwt:
    header: Authorization
    secret: alexander1234rudnmabdmasbmdDjabcjhabajsnadka
    sessionTime: 1200000000
server:
    port: ${PORT:8080}
spring:
    datasource:
        driver-class-name: org.postgresql.Driver
        password: ${SPRING_DATASOURCE_PASSWORD:postgres}
        platform: postgres
        url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/url_shortcut}
        username: ${SPRING_DATASOURCE_USERNAME:postgres}
    jpa:
        database: POSTGRESQL
        database-platform: org.hibernate.dialect.PostgreSQLDialect
        generate-ddl: false
        hibernate:
            ddl-auto: none
        open-in-view: false
        show-sql: true
    main:
        allow-bean-definition-overriding: true
    servlet:
        multipart:
            max-file-size: 10000000
            max-request-size: 10000000
